# Makefile für den Report

.PHONY: clean

WikiDataReportDBPRO.pdf: WikiDataReportDBPRO.tex
	pdflatex $<

clean:
	rm -f *.aux *.bbl *.blg *-blx.bib *.lof *.log *.lot *.fls *.out *.toc *.xml WikiDataReportDBPRO.pdf
